# Generated by Django 6.0.5 on 2026-05-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options_remove_product_min_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
