# Generated by Django 6.0.5 on 2026-05-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='note',
            new_name='notes',
        ),
    ]
