# Generated by Django 6.0.5 on 2026-05-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_note_stocktransaction_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The unique secret code required for new user registration.', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this invitation code is active and valid for use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
